#ifndef __DEBUG_RESOLUTION_H__
#define __DEBUG_RESOLUTION_H__

//1 resolution is on , 0 is off
#define RESOLUTION_DEBUG_ON 1

#define RESOLUTION_DEFAULT			1		//960 * 640
#define RESOLUTION_IPAD				2		//1024 * 768
#define RESOLUTION_IPAD_RETAIN		3		//2048 * 1536
#define RESOLUTION_IPHONE5			4		//1136 * 640
#define RESOLUTION_IOS_NO_RETAIN	5		//480 * 320
#define RESOLUTION_ANDROID_UNKONW	6		//RESOLUTION_ANDROID_UNKONW_WIDTH * RESOLUTION_ANDROID_UNKONW_HEIGHT
// RESOLUTION_ANDROID_UNKONW_WIDTH >= RESOLUTION_ANDROID_UNKONW_HEIGHT no matter SCREEN_ORIENTATION is SCREEN_LANDSCAPE or SCREEN_PORTRAIT
#define RESOLUTION_ANDROID_UNKONW_WIDTH 1136
#define RESOLUTION_ANDROID_UNKONW_HEIGHT 640
//select one resolution
#define NOW_RESOLUTION RESOLUTION_ANDROID_UNKONW

#endif